/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Windows;

import Functions.Company;
import java.io.File;
import java.io.PrintWriter;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/**
 *
 * @author santi
 */
public class MainInterface extends javax.swing.JFrame {
    
    static Company cartoonnetwork;
    static Company disney;

    /**
     * Creates new form PruebaTabbed
     */
    public MainInterface(Company cartoonnetwork, Company disney, int[] initialQuantitiesN, int []initialQuantitiesD) {
        initComponents();
        
        this.cartoonnetwork = cartoonnetwork;
        this.disney = disney;
        
        // Jlabels CN y Disney
        JLabel[] qttySavedPartsLabelsNick = {qttyGuionesSavedNick, qttyEscenariosSavedNick, qttyAnimacionesSavedNick, qttyDoblajesSavedNick, qttyPlotTwistsSavedNick, qttyStandardCapsReadyNick, qttyPlotTwistsCapsReadyNick, gananciasLabel};
        cartoonnetwork.getDrive().setLabels(qttySavedPartsLabelsNick);
        
        JLabel[] qttySavedPartsLabelsDisney = {qttyGuionesSavedDisney, qttyEscenariosSavedDisney, qttyAnimacionesSavedDisney, qttyDoblajesSavedDisney, qttyPlotTwistsSavedDisney, qttyStandardCapsReadyDisney, qttyPlotTwistsCapsReadyDisney, gananciasLabelDisney};
        disney.getDrive().setLabels(qttySavedPartsLabelsDisney);
        
        // Labels PM, se encarga de actualizar diariamente los costos y las utilidades
        JLabel[] pmLabelsN = {pmStatus, costosLabel, utilidadesLabel, deadlineLabel, daysPassedLabelN, daysPassedLabelN}; // Aca pasar tmb el del grafico?
        cartoonnetwork.getPm().setLabels(pmLabelsN);
        
        JLabel[] pmLabelsD = {pmStatusDisney, costosLabelDisney, utilidadesLabelDisney, deadlineLabelDisney, daysPassedLabelD};
        disney.getPm().setLabels(pmLabelsD);
        
        // Labels Director
        JLabel[] directorLabelsN = {directorStatus, deadlineLabel, faultsLabel, discountedLabel};
        cartoonnetwork.getDirector().setLabels(directorLabelsN);
        
        JLabel[] directorLabelsD = {directorStatusDisney, deadlineLabelDisney, faultsLabelDisney, discountedLabelDisney};
        disney.getDirector().setLabels(directorLabelsD);
        
        
        cartoonnetwork.startEmployees();
        disney.startEmployees();
        
        this.qttyGuionistasCN.setText(String.valueOf(initialQuantitiesN[0]));
        this.qttyEscenariosCN.setText(String.valueOf(initialQuantitiesN[1]));
        this.qttyAnimadoresCN.setText(String.valueOf(initialQuantitiesN[2]));
        this.qttyDobladoresCN.setText(String.valueOf(initialQuantitiesN[3]));
        this.qttyGuionistasPlotTwistsCN.setText(String.valueOf(initialQuantitiesN[4]));
        this.qttyEnsambladoresCN.setText(String.valueOf(initialQuantitiesN[5]));
        
        this.GuionistasNick.setText(String.valueOf(initialQuantitiesN[0]));
        this.EscenariosNick.setText(String.valueOf(initialQuantitiesN[1]));
        this.AnimadoresNick.setText(String.valueOf(initialQuantitiesN[2]));
        this.DobladoresNick.setText(String.valueOf(initialQuantitiesN[3]));
        this.GuionistasPlotTwistsNick.setText(String.valueOf(initialQuantitiesN[4]));
        this.EnsambladoresNick.setText(String.valueOf(initialQuantitiesN[5]));
        
        this.qttyGuionistasDisney.setText(String.valueOf(initialQuantitiesD[0]));
        this.qttyEscenariosDisney.setText(String.valueOf(initialQuantitiesD[1]));
        this.qttyAnimadoresDisney.setText(String.valueOf(initialQuantitiesD[2]));
        this.qttyDobladoresDisney.setText(String.valueOf(initialQuantitiesD[3]));
        this.qttyGuionistasPlotTwistsDisney.setText(String.valueOf(initialQuantitiesD[4]));
        this.qttyEnsambladoresDisney.setText(String.valueOf(initialQuantitiesD[5]));
        
        this.GuionistasDisney.setText(String.valueOf(initialQuantitiesD[0]));
        this.EscenariosDisney.setText(String.valueOf(initialQuantitiesD[1]));
        this.AnimadoresDisney.setText(String.valueOf(initialQuantitiesD[2]));
        this.DobladoresDisney.setText(String.valueOf(initialQuantitiesD[3]));
        this.GuionistasPlotTwistsDisney.setText(String.valueOf(initialQuantitiesD[4]));
        this.EnsambladoresDisney.setText(String.valueOf(initialQuantitiesD[5]));
        
        this.ammount.setText(Integer.toString(cartoonnetwork.getDeadline()));
        this.dia.setText(Integer.toString(cartoonnetwork.getDayDuration()));
        this.deadlineLabel.setText(Integer.toString(cartoonnetwork.getDeadline()));
        this.deadlineLabelDisney.setText(Integer.toString(disney.getDeadline()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        capsPlotTwistReadyLabel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ConfigurationDashboard = new javax.swing.JPanel();
        txt = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        ensambladorLabel1 = new javax.swing.JLabel();
        plotTwistLabel1 = new javax.swing.JLabel();
        doblajeLabel1 = new javax.swing.JLabel();
        animadorLabel1 = new javax.swing.JLabel();
        escenariosLabel1 = new javax.swing.JLabel();
        guionistasLabel1 = new javax.swing.JLabel();
        EnsambladoresNick = new javax.swing.JLabel();
        removeEnsamblador1 = new javax.swing.JButton();
        addEnsamblador1 = new javax.swing.JButton();
        GuionistasPlotTwistsNick = new javax.swing.JLabel();
        removePlotTwist1 = new javax.swing.JButton();
        addPlotTwist1 = new javax.swing.JButton();
        DobladoresNick = new javax.swing.JLabel();
        removeDoblaje1 = new javax.swing.JButton();
        addDoblaje1 = new javax.swing.JButton();
        removeAnimador1 = new javax.swing.JButton();
        addAnimador1 = new javax.swing.JButton();
        removeEscenarios1 = new javax.swing.JButton();
        addEscenarios1 = new javax.swing.JButton();
        removeGuionista2 = new javax.swing.JButton();
        addGuionista2 = new javax.swing.JButton();
        GuionistasNick = new javax.swing.JLabel();
        AnimadoresNick = new javax.swing.JLabel();
        EscenariosNick = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        guionistasLabel2 = new javax.swing.JLabel();
        escenariosLabel2 = new javax.swing.JLabel();
        removeGuionista3 = new javax.swing.JButton();
        addGuionista3 = new javax.swing.JButton();
        GuionistasDisney = new javax.swing.JLabel();
        EscenariosDisney = new javax.swing.JLabel();
        removeEscenarios2 = new javax.swing.JButton();
        addEscenarios2 = new javax.swing.JButton();
        removeAnimador2 = new javax.swing.JButton();
        AnimadoresDisney = new javax.swing.JLabel();
        addAnimador2 = new javax.swing.JButton();
        removeDoblaje2 = new javax.swing.JButton();
        DobladoresDisney = new javax.swing.JLabel();
        addDoblaje2 = new javax.swing.JButton();
        removePlotTwist2 = new javax.swing.JButton();
        GuionistasPlotTwistsDisney = new javax.swing.JLabel();
        addPlotTwist2 = new javax.swing.JButton();
        removeEnsamblador2 = new javax.swing.JButton();
        EnsambladoresDisney = new javax.swing.JLabel();
        addEnsamblador2 = new javax.swing.JButton();
        animadorLabel2 = new javax.swing.JLabel();
        doblajeLabel2 = new javax.swing.JLabel();
        plotTwistLabel2 = new javax.swing.JLabel();
        ensambladorLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        deadline = new javax.swing.JLabel();
        dayDuration = new javax.swing.JLabel();
        removeDia = new javax.swing.JButton();
        removeAmmount = new javax.swing.JButton();
        addAmmount = new javax.swing.JButton();
        addDia = new javax.swing.JButton();
        dia = new javax.swing.JLabel();
        ammount = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        NickelodeonDash = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        GuionesSavedLabel = new javax.swing.JLabel();
        qttyGuionesSavedNick = new javax.swing.JLabel();
        qttyEscenariosSavedNick = new javax.swing.JLabel();
        AnimacionesSavedLabel = new javax.swing.JLabel();
        qttyAnimacionesSavedNick = new javax.swing.JLabel();
        doblajesSavedLabel3 = new javax.swing.JLabel();
        qttyDoblajesSavedNick = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        faultsLabelText = new javax.swing.JLabel();
        faultsLabel = new javax.swing.JLabel();
        pmStatusLabel = new javax.swing.JLabel();
        pmStatus = new javax.swing.JLabel();
        directorStatusLabel = new javax.swing.JLabel();
        directorStatus = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        capsReadyLabel = new javax.swing.JLabel();
        qttyStandardCapsReadyNick = new javax.swing.JLabel();
        qttyPlotTwistsCapsReadyNick = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        EscenariosSavedLabel = new javax.swing.JLabel();
        plotTwistsSavedLabel4 = new javax.swing.JLabel();
        qttyPlotTwistsSavedNick = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        discountedLabelText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        deadlineLabelText = new javax.swing.JLabel();
        costosLabelText1 = new javax.swing.JLabel();
        costosLabelText = new javax.swing.JLabel();
        gananciaLabelText = new javax.swing.JLabel();
        gananciasLabel = new javax.swing.JLabel();
        costosLabel = new javax.swing.JLabel();
        utilidadesLabel = new javax.swing.JLabel();
        deadlineLabel = new javax.swing.JLabel();
        daysPassedLabelN = new javax.swing.JLabel();
        discountedLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        DisneyDash = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        gananciaLabelText1 = new javax.swing.JLabel();
        costosLabelText2 = new javax.swing.JLabel();
        costosLabelText3 = new javax.swing.JLabel();
        gananciasLabelDisney = new javax.swing.JLabel();
        costosLabelDisney = new javax.swing.JLabel();
        utilidadesLabelDisney = new javax.swing.JLabel();
        deadlineLabelText1 = new javax.swing.JLabel();
        deadlineLabelDisney = new javax.swing.JLabel();
        discountedLabelText1 = new javax.swing.JLabel();
        discountedLabelDisney = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        daysPassedLabelD = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        capsPlotTwistReadyLabel1 = new javax.swing.JLabel();
        capsReadyLabel1 = new javax.swing.JLabel();
        qttyStandardCapsReadyDisney = new javax.swing.JLabel();
        qttyPlotTwistsCapsReadyDisney = new javax.swing.JLabel();
        GuionesSavedLabelD = new javax.swing.JLabel();
        qttyGuionesSavedDisney = new javax.swing.JLabel();
        EscenariosSavedLabelD = new javax.swing.JLabel();
        qttyEscenariosSavedDisney = new javax.swing.JLabel();
        AnimacionesSavedLabelD = new javax.swing.JLabel();
        qttyAnimacionesSavedDisney = new javax.swing.JLabel();
        doblajesSavedLabelD = new javax.swing.JLabel();
        qttyDoblajesSavedDisney = new javax.swing.JLabel();
        plotTwistsSavedLabelD = new javax.swing.JLabel();
        qttyPlotTwistsSavedDisney = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        pmStatusLabelD = new javax.swing.JLabel();
        directorStatusLabelD = new javax.swing.JLabel();
        pmStatusDisney = new javax.swing.JLabel();
        directorStatusDisney = new javax.swing.JLabel();
        faultsLabelText1 = new javax.swing.JLabel();
        faultsLabelDisney = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        dinseyFondo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        capsPlotTwistReadyLabel.setText("Capitulos PlotTwists Listos:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ConfigurationDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt.setBackground(new java.awt.Color(51, 51, 51));
        txt.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        txt.setForeground(new java.awt.Color(204, 204, 204));
        txt.setText("Salvar cambios");
        txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActionPerformed(evt);
            }
        });
        ConfigurationDashboard.add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, -1, -1));

        jPanel9.setBackground(new java.awt.Color(102, 102, 102));
        jPanel9.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NickelodeonLogoTiny.png"))); // NOI18N
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 383, -1, -1));

        ensambladorLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ensambladorLabel1.setForeground(new java.awt.Color(0, 0, 0));
        ensambladorLabel1.setText("Numero de Ensambladores:");
        jPanel9.add(ensambladorLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        plotTwistLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        plotTwistLabel1.setForeground(new java.awt.Color(0, 0, 0));
        plotTwistLabel1.setText("Numero de guionistas de PT:");
        jPanel9.add(plotTwistLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        doblajeLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        doblajeLabel1.setForeground(new java.awt.Color(0, 0, 0));
        doblajeLabel1.setText("Numero de actores de doblaje:");
        jPanel9.add(doblajeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        animadorLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        animadorLabel1.setForeground(new java.awt.Color(0, 0, 0));
        animadorLabel1.setText("Numero de animadores:");
        jPanel9.add(animadorLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        escenariosLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        escenariosLabel1.setForeground(new java.awt.Color(0, 0, 0));
        escenariosLabel1.setText("Numero de diseñadores:");
        jPanel9.add(escenariosLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        guionistasLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        guionistasLabel1.setForeground(new java.awt.Color(0, 0, 0));
        guionistasLabel1.setText("Numero de guionistas:");
        jPanel9.add(guionistasLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        EnsambladoresNick.setBackground(new java.awt.Color(0, 0, 0));
        EnsambladoresNick.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        EnsambladoresNick.setForeground(new java.awt.Color(0, 0, 0));
        EnsambladoresNick.setText("0");
        jPanel9.add(EnsambladoresNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, -1));

        removeEnsamblador1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        removeEnsamblador1.setText("-");
        removeEnsamblador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEnsamblador1ActionPerformed(evt);
            }
        });
        jPanel9.add(removeEnsamblador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, -1));

        addEnsamblador1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addEnsamblador1.setText("+");
        addEnsamblador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEnsamblador1ActionPerformed(evt);
            }
        });
        jPanel9.add(addEnsamblador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        GuionistasPlotTwistsNick.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        GuionistasPlotTwistsNick.setForeground(new java.awt.Color(0, 0, 0));
        GuionistasPlotTwistsNick.setText("0");
        jPanel9.add(GuionistasPlotTwistsNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        removePlotTwist1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        removePlotTwist1.setText("-");
        removePlotTwist1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePlotTwist1ActionPerformed(evt);
            }
        });
        jPanel9.add(removePlotTwist1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        addPlotTwist1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addPlotTwist1.setText("+");
        addPlotTwist1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlotTwist1ActionPerformed(evt);
            }
        });
        jPanel9.add(addPlotTwist1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        DobladoresNick.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        DobladoresNick.setForeground(new java.awt.Color(0, 0, 0));
        DobladoresNick.setText("0");
        jPanel9.add(DobladoresNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        removeDoblaje1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        removeDoblaje1.setText("-");
        removeDoblaje1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDoblaje1ActionPerformed(evt);
            }
        });
        jPanel9.add(removeDoblaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        addDoblaje1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addDoblaje1.setText("+");
        addDoblaje1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDoblaje1ActionPerformed(evt);
            }
        });
        jPanel9.add(addDoblaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        removeAnimador1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        removeAnimador1.setText("-");
        removeAnimador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAnimador1ActionPerformed(evt);
            }
        });
        jPanel9.add(removeAnimador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        addAnimador1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addAnimador1.setText("+");
        addAnimador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAnimador1ActionPerformed(evt);
            }
        });
        jPanel9.add(addAnimador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        removeEscenarios1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        removeEscenarios1.setText("-");
        removeEscenarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEscenarios1ActionPerformed(evt);
            }
        });
        jPanel9.add(removeEscenarios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        addEscenarios1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addEscenarios1.setText("+");
        addEscenarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEscenarios1ActionPerformed(evt);
            }
        });
        jPanel9.add(addEscenarios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        removeGuionista2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        removeGuionista2.setText("-");
        removeGuionista2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeGuionista2ActionPerformed(evt);
            }
        });
        jPanel9.add(removeGuionista2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        addGuionista2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addGuionista2.setText("+");
        addGuionista2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGuionista2ActionPerformed(evt);
            }
        });
        jPanel9.add(addGuionista2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        GuionistasNick.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        GuionistasNick.setForeground(new java.awt.Color(0, 0, 0));
        GuionistasNick.setText("0");
        jPanel9.add(GuionistasNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        AnimadoresNick.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        AnimadoresNick.setForeground(new java.awt.Color(0, 0, 0));
        AnimadoresNick.setText("0");
        jPanel9.add(AnimadoresNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        EscenariosNick.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        EscenariosNick.setForeground(new java.awt.Color(0, 0, 0));
        EscenariosNick.setText("0");
        jPanel9.add(EscenariosNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoDisneyTiny.png"))); // NOI18N
        jLabel26.setText("Cartoon Network");
        jPanel9.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 210, -1));

        ConfigurationDashboard.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 310, 480));

        jPanel11.setBackground(new java.awt.Color(0, 51, 153));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoDisneyTiny.png"))); // NOI18N
        jLabel19.setText("Disney");
        jPanel11.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 80, -1));

        guionistasLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        guionistasLabel2.setForeground(new java.awt.Color(0, 0, 0));
        guionistasLabel2.setText("Numero de guionistas:");
        jPanel11.add(guionistasLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        escenariosLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        escenariosLabel2.setForeground(new java.awt.Color(0, 0, 0));
        escenariosLabel2.setText("Numero de diseñadores:");
        jPanel11.add(escenariosLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        removeGuionista3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        removeGuionista3.setText("-");
        removeGuionista3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeGuionista3ActionPerformed(evt);
            }
        });
        jPanel11.add(removeGuionista3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        addGuionista3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addGuionista3.setText("+");
        addGuionista3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGuionista3ActionPerformed(evt);
            }
        });
        jPanel11.add(addGuionista3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        GuionistasDisney.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        GuionistasDisney.setForeground(new java.awt.Color(0, 0, 0));
        GuionistasDisney.setText("0");
        jPanel11.add(GuionistasDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        EscenariosDisney.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        EscenariosDisney.setForeground(new java.awt.Color(0, 0, 0));
        EscenariosDisney.setText("0");
        jPanel11.add(EscenariosDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        removeEscenarios2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        removeEscenarios2.setText("-");
        removeEscenarios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEscenarios2ActionPerformed(evt);
            }
        });
        jPanel11.add(removeEscenarios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        addEscenarios2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addEscenarios2.setText("+");
        addEscenarios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEscenarios2ActionPerformed(evt);
            }
        });
        jPanel11.add(addEscenarios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        removeAnimador2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        removeAnimador2.setText("-");
        removeAnimador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAnimador2ActionPerformed(evt);
            }
        });
        jPanel11.add(removeAnimador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        AnimadoresDisney.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        AnimadoresDisney.setForeground(new java.awt.Color(0, 0, 0));
        AnimadoresDisney.setText("0");
        jPanel11.add(AnimadoresDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        addAnimador2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addAnimador2.setText("+");
        addAnimador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAnimador2ActionPerformed(evt);
            }
        });
        jPanel11.add(addAnimador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        removeDoblaje2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        removeDoblaje2.setText("-");
        removeDoblaje2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDoblaje2ActionPerformed(evt);
            }
        });
        jPanel11.add(removeDoblaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        DobladoresDisney.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        DobladoresDisney.setForeground(new java.awt.Color(0, 0, 0));
        DobladoresDisney.setText("0");
        jPanel11.add(DobladoresDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 10, -1));

        addDoblaje2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addDoblaje2.setText("+");
        addDoblaje2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDoblaje2ActionPerformed(evt);
            }
        });
        jPanel11.add(addDoblaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        removePlotTwist2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        removePlotTwist2.setText("-");
        removePlotTwist2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePlotTwist2ActionPerformed(evt);
            }
        });
        jPanel11.add(removePlotTwist2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        GuionistasPlotTwistsDisney.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        GuionistasPlotTwistsDisney.setForeground(new java.awt.Color(0, 0, 0));
        GuionistasPlotTwistsDisney.setText("0");
        jPanel11.add(GuionistasPlotTwistsDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        addPlotTwist2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addPlotTwist2.setText("+");
        addPlotTwist2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlotTwist2ActionPerformed(evt);
            }
        });
        jPanel11.add(addPlotTwist2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        removeEnsamblador2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        removeEnsamblador2.setText("-");
        removeEnsamblador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEnsamblador2ActionPerformed(evt);
            }
        });
        jPanel11.add(removeEnsamblador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, -1));

        EnsambladoresDisney.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        EnsambladoresDisney.setForeground(new java.awt.Color(0, 0, 0));
        EnsambladoresDisney.setText("0");
        jPanel11.add(EnsambladoresDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));

        addEnsamblador2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addEnsamblador2.setText("+");
        addEnsamblador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEnsamblador2ActionPerformed(evt);
            }
        });
        jPanel11.add(addEnsamblador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, -1));

        animadorLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        animadorLabel2.setForeground(new java.awt.Color(0, 0, 0));
        animadorLabel2.setText("Numero de animadores:");
        jPanel11.add(animadorLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        doblajeLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        doblajeLabel2.setForeground(new java.awt.Color(0, 0, 0));
        doblajeLabel2.setText("Numero de actores de doblaje:");
        jPanel11.add(doblajeLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        plotTwistLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        plotTwistLabel2.setForeground(new java.awt.Color(0, 0, 0));
        plotTwistLabel2.setText("Numero de guionistas de PT:");
        jPanel11.add(plotTwistLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        ensambladorLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ensambladorLabel2.setForeground(new java.awt.Color(0, 0, 0));
        ensambladorLabel2.setText("Numero de Ensambladores:");
        jPanel11.add(ensambladorLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        ConfigurationDashboard.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 330, 480));

        jPanel10.setBackground(new java.awt.Color(0, 153, 102));
        jPanel10.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deadline.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        deadline.setForeground(new java.awt.Color(0, 0, 0));
        deadline.setText("Deadline:");
        jPanel10.add(deadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        dayDuration.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dayDuration.setForeground(new java.awt.Color(0, 0, 0));
        dayDuration.setText("Duracion de un dia:");
        jPanel10.add(dayDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        removeDia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        removeDia.setText("-");
        removeDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDiaActionPerformed(evt);
            }
        });
        jPanel10.add(removeDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        removeAmmount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        removeAmmount.setText("-");
        removeAmmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAmmountActionPerformed(evt);
            }
        });
        jPanel10.add(removeAmmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        addAmmount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addAmmount.setText("+");
        addAmmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAmmountActionPerformed(evt);
            }
        });
        jPanel10.add(addAmmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        addDia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addDia.setText("+");
        addDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDiaActionPerformed(evt);
            }
        });
        jPanel10.add(addDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        dia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dia.setForeground(new java.awt.Color(0, 0, 0));
        dia.setText("0");
        jPanel10.add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        ammount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ammount.setForeground(new java.awt.Color(0, 0, 0));
        ammount.setText("0");
        jPanel10.add(ammount, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        ConfigurationDashboard.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 290, 130));

        jPanel12.setBackground(new java.awt.Color(51, 51, 51));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Ajustes");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel17)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        ConfigurationDashboard.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 340, 60));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Configuracion.png"))); // NOI18N
        ConfigurationDashboard.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPNG/fondoconfig1.jpg"))); // NOI18N
        ConfigurationDashboard.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(-12, 0, 1020, 600));

        jTabbedPane1.addTab("ConfigurationDashboard", ConfigurationDashboard);

        NickelodeonDash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NickelodeonLogo.png"))); // NOI18N
        NickelodeonDash.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, 130));

        GuionesSavedLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        GuionesSavedLabel.setText("Guiones:");
        NickelodeonDash.add(GuionesSavedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        qttyGuionesSavedNick.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        qttyGuionesSavedNick.setText("0");
        NickelodeonDash.add(qttyGuionesSavedNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, -1));

        qttyEscenariosSavedNick.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        qttyEscenariosSavedNick.setText("0");
        NickelodeonDash.add(qttyEscenariosSavedNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, -1));

        AnimacionesSavedLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        AnimacionesSavedLabel.setText("Animaciones");
        NickelodeonDash.add(AnimacionesSavedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        qttyAnimacionesSavedNick.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        qttyAnimacionesSavedNick.setText("0");
        NickelodeonDash.add(qttyAnimacionesSavedNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, -1));

        doblajesSavedLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        doblajesSavedLabel3.setText("Doblajes:");
        NickelodeonDash.add(doblajesSavedLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        qttyDoblajesSavedNick.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        qttyDoblajesSavedNick.setText("0");
        NickelodeonDash.add(qttyDoblajesSavedNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        faultsLabelText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        faultsLabelText.setText("Faltas del Project Manager:");
        jPanel1.add(faultsLabelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        faultsLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        faultsLabel.setText("0");
        jPanel1.add(faultsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        pmStatusLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pmStatusLabel.setText("Project Manager Status:");
        jPanel1.add(pmStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        pmStatus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pmStatus.setText("...");
        jPanel1.add(pmStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        directorStatusLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        directorStatusLabel.setText("Director Status:");
        jPanel1.add(directorStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        directorStatus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        directorStatus.setText("...");
        jPanel1.add(directorStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        jPanel5.setBackground(new java.awt.Color(232, 114, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 330, -1));

        jLabel14.setBackground(new java.awt.Color(232, 114, 0));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(232, 114, 0));
        jLabel14.setText("Estados");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 110, -1));

        jPanel7.setBackground(new java.awt.Color(19, 139, 30));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        NickelodeonDash.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 360, 230));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(42, 140, 35));
        jLabel13.setText("Drive");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        capsReadyLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        capsReadyLabel.setText("Capitulos:");
        jPanel2.add(capsReadyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        qttyStandardCapsReadyNick.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        qttyStandardCapsReadyNick.setText("0");
        jPanel2.add(qttyStandardCapsReadyNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        qttyPlotTwistsCapsReadyNick.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        qttyPlotTwistsCapsReadyNick.setText("0");
        jPanel2.add(qttyPlotTwistsCapsReadyNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gary.png"))); // NOI18N
        jLabel16.setText("Capitulos PT:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 80, 30));

        EscenariosSavedLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        EscenariosSavedLabel.setText("Escenarios:");
        jPanel2.add(EscenariosSavedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        plotTwistsSavedLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        plotTwistsSavedLabel4.setText("PlotTwists:");
        jPanel2.add(plotTwistsSavedLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        qttyPlotTwistsSavedNick.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        qttyPlotTwistsSavedNick.setText("0");
        jPanel2.add(qttyPlotTwistsSavedNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        NickelodeonDash.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 330, 400));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        discountedLabelText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        discountedLabelText.setText("PM discount:");
        jPanel3.add(discountedLabelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Dias totales transcurridos:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        deadlineLabelText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        deadlineLabelText.setText("Deadline:");
        jPanel3.add(deadlineLabelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        costosLabelText1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        costosLabelText1.setText("Utilidad:");
        jPanel3.add(costosLabelText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        costosLabelText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        costosLabelText.setText("Costos:");
        jPanel3.add(costosLabelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        gananciaLabelText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gananciaLabelText.setText("Ganancias:");
        jPanel3.add(gananciaLabelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        gananciasLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gananciasLabel.setText("0");
        jPanel3.add(gananciasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        costosLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        costosLabel.setText("0");
        jPanel3.add(costosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        utilidadesLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        utilidadesLabel.setText("0");
        jPanel3.add(utilidadesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        deadlineLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        deadlineLabel.setText("0");
        jPanel3.add(deadlineLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        daysPassedLabelN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        daysPassedLabelN.setText("0");
        jPanel3.add(daysPassedLabelN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        discountedLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        discountedLabel.setText("0");
        jPanel3.add(discountedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 51, 255));
        jLabel15.setText("Totales");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 100, -1));

        NickelodeonDash.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, 210, 300));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPNG/image (2).png"))); // NOI18N
        NickelodeonDash.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1030, 680));

        jTabbedPane1.addTab("Cartoon Network", NickelodeonDash);

        DisneyDash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(34, 94, 135));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gananciaLabelText1.setBackground(new java.awt.Color(255, 255, 255));
        gananciaLabelText1.setForeground(new java.awt.Color(255, 255, 255));
        gananciaLabelText1.setText("Ganancias:");
        jPanel17.add(gananciaLabelText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        costosLabelText2.setBackground(new java.awt.Color(255, 255, 255));
        costosLabelText2.setForeground(new java.awt.Color(255, 255, 255));
        costosLabelText2.setText("Costos:");
        jPanel17.add(costosLabelText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        costosLabelText3.setBackground(new java.awt.Color(255, 255, 255));
        costosLabelText3.setForeground(new java.awt.Color(255, 255, 255));
        costosLabelText3.setText("Utilidad:");
        jPanel17.add(costosLabelText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        gananciasLabelDisney.setBackground(new java.awt.Color(255, 255, 255));
        gananciasLabelDisney.setForeground(new java.awt.Color(255, 255, 255));
        gananciasLabelDisney.setText("0");
        jPanel17.add(gananciasLabelDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        costosLabelDisney.setBackground(new java.awt.Color(255, 255, 255));
        costosLabelDisney.setForeground(new java.awt.Color(255, 255, 255));
        costosLabelDisney.setText("0");
        jPanel17.add(costosLabelDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        utilidadesLabelDisney.setBackground(new java.awt.Color(255, 255, 255));
        utilidadesLabelDisney.setForeground(new java.awt.Color(255, 255, 255));
        utilidadesLabelDisney.setText("0");
        jPanel17.add(utilidadesLabelDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        deadlineLabelText1.setBackground(new java.awt.Color(255, 255, 255));
        deadlineLabelText1.setForeground(new java.awt.Color(255, 255, 255));
        deadlineLabelText1.setText("Deadline:");
        jPanel17.add(deadlineLabelText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        deadlineLabelDisney.setBackground(new java.awt.Color(255, 255, 255));
        deadlineLabelDisney.setForeground(new java.awt.Color(255, 255, 255));
        deadlineLabelDisney.setText("0");
        jPanel17.add(deadlineLabelDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        discountedLabelText1.setBackground(new java.awt.Color(255, 255, 255));
        discountedLabelText1.setForeground(new java.awt.Color(255, 255, 255));
        discountedLabelText1.setText("PM discount:");
        jPanel17.add(discountedLabelText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        discountedLabelDisney.setBackground(new java.awt.Color(255, 255, 255));
        discountedLabelDisney.setForeground(new java.awt.Color(255, 255, 255));
        discountedLabelDisney.setText("0");
        jPanel17.add(discountedLabelDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Dias totales transcurridos:");
        jPanel17.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        daysPassedLabelD.setBackground(new java.awt.Color(255, 255, 255));
        daysPassedLabelD.setForeground(new java.awt.Color(255, 255, 255));
        daysPassedLabelD.setText("0");
        jPanel17.add(daysPassedLabelD, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        jPanel18.setBackground(new java.awt.Color(185, 219, 253));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 198, -1));

        jLabel23.setBackground(new java.awt.Color(185, 219, 253));
        jLabel23.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(185, 219, 253));
        jLabel23.setText("Totales");
        jPanel17.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 155, -1));

        DisneyDash.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 220, 300));

        jPanel15.setBackground(new java.awt.Color(56, 55, 125));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        capsPlotTwistReadyLabel1.setBackground(new java.awt.Color(255, 255, 255));
        capsPlotTwistReadyLabel1.setForeground(new java.awt.Color(255, 255, 255));
        capsPlotTwistReadyLabel1.setText("Capitulos PT");
        jPanel15.add(capsPlotTwistReadyLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        capsReadyLabel1.setBackground(new java.awt.Color(255, 255, 255));
        capsReadyLabel1.setForeground(new java.awt.Color(255, 255, 255));
        capsReadyLabel1.setText("Capitulos Standar Listos:");
        jPanel15.add(capsReadyLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        qttyStandardCapsReadyDisney.setBackground(new java.awt.Color(255, 255, 255));
        qttyStandardCapsReadyDisney.setForeground(new java.awt.Color(255, 255, 255));
        qttyStandardCapsReadyDisney.setText("0");
        jPanel15.add(qttyStandardCapsReadyDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        qttyPlotTwistsCapsReadyDisney.setBackground(new java.awt.Color(255, 255, 255));
        qttyPlotTwistsCapsReadyDisney.setForeground(new java.awt.Color(255, 255, 255));
        qttyPlotTwistsCapsReadyDisney.setText("0");
        jPanel15.add(qttyPlotTwistsCapsReadyDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        GuionesSavedLabelD.setBackground(new java.awt.Color(255, 255, 255));
        GuionesSavedLabelD.setForeground(new java.awt.Color(255, 255, 255));
        GuionesSavedLabelD.setText("Guiones en el Drive:");
        jPanel15.add(GuionesSavedLabelD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        qttyGuionesSavedDisney.setBackground(new java.awt.Color(255, 255, 255));
        qttyGuionesSavedDisney.setForeground(new java.awt.Color(255, 255, 255));
        qttyGuionesSavedDisney.setText("0");
        jPanel15.add(qttyGuionesSavedDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        EscenariosSavedLabelD.setBackground(new java.awt.Color(255, 255, 255));
        EscenariosSavedLabelD.setForeground(new java.awt.Color(255, 255, 255));
        EscenariosSavedLabelD.setText("Escenarios en el Drive:");
        jPanel15.add(EscenariosSavedLabelD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        qttyEscenariosSavedDisney.setBackground(new java.awt.Color(255, 255, 255));
        qttyEscenariosSavedDisney.setForeground(new java.awt.Color(255, 255, 255));
        qttyEscenariosSavedDisney.setText("0");
        jPanel15.add(qttyEscenariosSavedDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        AnimacionesSavedLabelD.setBackground(new java.awt.Color(255, 255, 255));
        AnimacionesSavedLabelD.setForeground(new java.awt.Color(255, 255, 255));
        AnimacionesSavedLabelD.setText("Animaciones en el Drive:");
        jPanel15.add(AnimacionesSavedLabelD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        qttyAnimacionesSavedDisney.setBackground(new java.awt.Color(255, 255, 255));
        qttyAnimacionesSavedDisney.setForeground(new java.awt.Color(255, 255, 255));
        qttyAnimacionesSavedDisney.setText("0");
        jPanel15.add(qttyAnimacionesSavedDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        doblajesSavedLabelD.setBackground(new java.awt.Color(255, 255, 255));
        doblajesSavedLabelD.setForeground(new java.awt.Color(255, 255, 255));
        doblajesSavedLabelD.setText("Doblajes en el Drive:");
        jPanel15.add(doblajesSavedLabelD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        qttyDoblajesSavedDisney.setBackground(new java.awt.Color(255, 255, 255));
        qttyDoblajesSavedDisney.setForeground(new java.awt.Color(255, 255, 255));
        qttyDoblajesSavedDisney.setText("0");
        jPanel15.add(qttyDoblajesSavedDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        plotTwistsSavedLabelD.setBackground(new java.awt.Color(255, 255, 255));
        plotTwistsSavedLabelD.setForeground(new java.awt.Color(255, 255, 255));
        plotTwistsSavedLabelD.setText("PlotTwists en el Drive:");
        jPanel15.add(plotTwistsSavedLabelD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        qttyPlotTwistsSavedDisney.setBackground(new java.awt.Color(255, 255, 255));
        qttyPlotTwistsSavedDisney.setForeground(new java.awt.Color(255, 255, 255));
        qttyPlotTwistsSavedDisney.setText("0");
        jPanel15.add(qttyPlotTwistsSavedDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        jLabel22.setBackground(new java.awt.Color(153, 0, 255));
        jLabel22.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 0, 255));
        jLabel22.setText("Drive");
        jPanel15.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));
        jPanel15.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        DisneyDash.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 340, 420));

        jPanel13.setBackground(new java.awt.Color(7, 37, 57));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pmStatusLabelD.setBackground(new java.awt.Color(255, 255, 255));
        pmStatusLabelD.setForeground(new java.awt.Color(255, 255, 255));
        pmStatusLabelD.setText("PM:");
        jPanel13.add(pmStatusLabelD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        directorStatusLabelD.setBackground(new java.awt.Color(255, 255, 255));
        directorStatusLabelD.setForeground(new java.awt.Color(255, 255, 255));
        directorStatusLabelD.setText("Director:");
        jPanel13.add(directorStatusLabelD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        pmStatusDisney.setBackground(new java.awt.Color(255, 255, 255));
        pmStatusDisney.setForeground(new java.awt.Color(255, 255, 255));
        pmStatusDisney.setText("...");
        jPanel13.add(pmStatusDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        directorStatusDisney.setBackground(new java.awt.Color(255, 255, 255));
        directorStatusDisney.setForeground(new java.awt.Color(255, 255, 255));
        directorStatusDisney.setText("...");
        jPanel13.add(directorStatusDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        faultsLabelText1.setBackground(new java.awt.Color(255, 255, 255));
        faultsLabelText1.setForeground(new java.awt.Color(255, 255, 255));
        faultsLabelText1.setText("PM faults");
        jPanel13.add(faultsLabelText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        faultsLabelDisney.setBackground(new java.awt.Color(255, 255, 255));
        faultsLabelDisney.setForeground(new java.awt.Color(255, 255, 255));
        faultsLabelDisney.setText("0");
        jPanel13.add(faultsLabelDisney, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        jLabel20.setBackground(new java.awt.Color(147, 193, 252));
        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(147, 193, 252));
        jLabel20.setText("Estados");
        jPanel13.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 110, -1));

        DisneyDash.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 290, 280));
        DisneyDash.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, -50, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DisneyLogo.png"))); // NOI18N
        DisneyDash.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, -40, -1, -1));

        dinseyFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPNG/image.png"))); // NOI18N
        DisneyDash.add(dinseyFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1080, 610));

        jLabel3.setText("jLabel3");
        DisneyDash.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jTabbedPane1.addTab("DisneyChannel", DisneyDash);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1006, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDiaActionPerformed
        int nuevo = Integer.parseInt(dia.getText())+1000;
        dia.setText(String.valueOf(nuevo));
    }//GEN-LAST:event_addDiaActionPerformed

    private void addAmmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAmmountActionPerformed
        int nuevo = Integer.parseInt(ammount.getText())+1;
        ammount.setText(String.valueOf(nuevo));
    }//GEN-LAST:event_addAmmountActionPerformed

    private void removeAmmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAmmountActionPerformed
        if(Integer.parseInt(ammount.getText())== 1){
            JOptionPane.showMessageDialog(null, "SE DEBE TENER POR LO MENOS UN DIA COMO DEADLINE DE ENTREGA");
        } else {
            int nuevo = Integer.parseInt(ammount.getText())-1;
            ammount.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removeAmmountActionPerformed

    private void removeDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDiaActionPerformed
        if(Integer.parseInt(dia.getText())==2000){
            JOptionPane.showMessageDialog(null, "EL DIA DEBE DURAR MINIMO 2000MS");
        } else {
            int nuevo = Integer.parseInt(dia.getText())-1000;
            dia.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removeDiaActionPerformed

    private void addEnsamblador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEnsamblador2ActionPerformed
        if (calculateQuantityD() == 13){
            JOptionPane.showMessageDialog(null, "SE HA SUPERADO LA CANTIDAD LIMITE DE TRABAJADORES!");
        } else {
            int nuevo = Integer.parseInt(EnsambladoresDisney.getText())+1;
            EnsambladoresDisney.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_addEnsamblador2ActionPerformed

    private void removeEnsamblador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEnsamblador2ActionPerformed
        if (Integer.parseInt(EnsambladoresDisney.getText()) == 1){
            JOptionPane.showMessageDialog(null, "NO SE PUEDE DEJAR UN DEPARTAMENTO SIN TRABAJADORES");
        } else{
            int nuevo = Integer.parseInt(EnsambladoresDisney.getText())-1;
            EnsambladoresDisney.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removeEnsamblador2ActionPerformed

    private void addPlotTwist2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlotTwist2ActionPerformed
        if (calculateQuantityD() == 13){
            JOptionPane.showMessageDialog(null, "SE HA SUPERADO LA CANTIDAD LIMITE DE TRABAJADORES!");
        } else {
            int nuevo = Integer.parseInt(GuionistasPlotTwistsDisney.getText())+1;
            GuionistasPlotTwistsDisney.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_addPlotTwist2ActionPerformed

    private void removePlotTwist2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePlotTwist2ActionPerformed
        if (Integer.parseInt(GuionistasPlotTwistsDisney.getText()) == 1){
            JOptionPane.showMessageDialog(null, "NO SE PUEDE DEJAR UN DEPARTAMENTO SIN TRABAJADORES");
        } else{
            int nuevo = Integer.parseInt(GuionistasPlotTwistsDisney.getText())-1;
            GuionistasPlotTwistsDisney.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removePlotTwist2ActionPerformed

    private void addDoblaje2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDoblaje2ActionPerformed
        if (calculateQuantityD() == 13){
            JOptionPane.showMessageDialog(null, "SE HA SUPERADO LA CANTIDAD LIMITE DE TRABAJADORES!");
        } else {
            int nuevo = Integer.parseInt(DobladoresDisney.getText())+1;
            DobladoresDisney.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_addDoblaje2ActionPerformed

    private void removeDoblaje2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDoblaje2ActionPerformed
        if (Integer.parseInt(DobladoresDisney.getText()) == 1){
            JOptionPane.showMessageDialog(null, "NO SE PUEDE DEJAR UN DEPARTAMENTO SIN TRABAJADORES");
        } else{
            int nuevo = Integer.parseInt(DobladoresDisney.getText())-1;
            DobladoresDisney.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removeDoblaje2ActionPerformed

    private void addAnimador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAnimador2ActionPerformed
        if (calculateQuantityD() == 13) {
            JOptionPane.showMessageDialog(null, "SE HA SUPERADO LA CANTIDAD LIMITE DE TRABAJADORES!");
        } else {
            int nuevo = Integer.parseInt(AnimadoresDisney.getText()) + 1;
            AnimadoresDisney.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_addAnimador2ActionPerformed

    private void removeAnimador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAnimador2ActionPerformed
        if (Integer.parseInt(AnimadoresDisney.getText()) == 1){
            JOptionPane.showMessageDialog(null, "NO SE PUEDE DEJAR UN DEPARTAMENTO SIN TRABAJADORES");
        } else{
            int nuevo = Integer.parseInt(AnimadoresDisney.getText())-1;
            AnimadoresDisney.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removeAnimador2ActionPerformed

    private void addEscenarios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEscenarios2ActionPerformed
        if (calculateQuantityD() == 13){
            JOptionPane.showMessageDialog(null, "SE HA SUPERADO LA CANTIDAD LIMITE DE TRABAJADORES!");
        } else {
            int nuevo = Integer.parseInt(EscenariosDisney.getText())+1;
            EscenariosDisney.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_addEscenarios2ActionPerformed

    private void removeEscenarios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEscenarios2ActionPerformed
        if (Integer.parseInt(EscenariosDisney.getText()) == 1){
            JOptionPane.showMessageDialog(null, "NO SE PUEDE DEJAR UN DEPARTAMENTO SIN TRABAJADORES");
        } else{
            int nuevo = Integer.parseInt(EscenariosDisney.getText())-1;
            EscenariosDisney.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removeEscenarios2ActionPerformed

    private void addGuionista3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGuionista3ActionPerformed
        if (calculateQuantityD() == 13){
            JOptionPane.showMessageDialog(null, "SE HA SUPERADO LA CANTIDAD LIMITE DE TRABAJADORES!");
        } else {
            int nuevo = Integer.parseInt(GuionistasDisney.getText())+1;
            GuionistasDisney.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_addGuionista3ActionPerformed

    private void removeGuionista3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeGuionista3ActionPerformed
        if (Integer.parseInt(GuionistasDisney.getText()) == 1){
            JOptionPane.showMessageDialog(null, "NO SE PUEDE DEJAR UN DEPARTAMENTO SIN TRABAJADORES");
        } else{
            int nuevo = Integer.parseInt(GuionistasDisney.getText())-1;
            GuionistasDisney.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removeGuionista3ActionPerformed

    private void addGuionista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGuionista2ActionPerformed
        if (calculateQuantityN() == 12){
            JOptionPane.showMessageDialog(null, "SE HA SUPERADO LA CANTIDAD LIMITE DE TRABAJADORES!");
        } else {
            int nuevo = Integer.parseInt(GuionistasNick.getText())+1;
            GuionistasNick.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_addGuionista2ActionPerformed

    private void removeGuionista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeGuionista2ActionPerformed
        if (Integer.parseInt(GuionistasNick.getText()) == 1){
            JOptionPane.showMessageDialog(null, "NO SE PUEDE DEJAR UN DEPARTAMENTO SIN TRABAJADORES");
        } else{
            int nuevo = Integer.parseInt(GuionistasNick.getText())-1;
            GuionistasNick.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removeGuionista2ActionPerformed

    private void addEscenarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEscenarios1ActionPerformed
        if (calculateQuantityN() == 12){
            JOptionPane.showMessageDialog(null, "SE HA SUPERADO LA CANTIDAD LIMITE DE TRABAJADORES!");
        } else {
            int nuevo = Integer.parseInt(EscenariosNick.getText())+1;
            EscenariosNick.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_addEscenarios1ActionPerformed

    private void removeEscenarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEscenarios1ActionPerformed
        if (Integer.parseInt(EscenariosNick.getText()) == 1){
            JOptionPane.showMessageDialog(null, "NO SE PUEDE DEJAR UN DEPARTAMENTO SIN TRABAJADORES");
        } else{
            int nuevo = Integer.parseInt(EscenariosNick.getText())-1;
            EscenariosNick.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removeEscenarios1ActionPerformed

    private void addAnimador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAnimador1ActionPerformed
        if (calculateQuantityN() == 12){
            JOptionPane.showMessageDialog(null, "SE HA SUPERADO LA CANTIDAD LIMITE DE TRABAJADORES!");
        } else {
            int nuevo = Integer.parseInt(AnimadoresNick.getText())+1;
            AnimadoresNick.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_addAnimador1ActionPerformed

    private void removeAnimador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAnimador1ActionPerformed
        if (Integer.parseInt(AnimadoresNick.getText()) == 1){
            JOptionPane.showMessageDialog(null, "NO SE PUEDE DEJAR UN DEPARTAMENTO SIN TRABAJADORES");
        } else{
            int nuevo = Integer.parseInt(AnimadoresNick.getText())-1;
            AnimadoresNick.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removeAnimador1ActionPerformed

    private void addDoblaje1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDoblaje1ActionPerformed
        if (calculateQuantityN() == 12){
            JOptionPane.showMessageDialog(null, "SE HA SUPERADO LA CANTIDAD LIMITE DE TRABAJADORES!");
        } else {
            int nuevo = Integer.parseInt(DobladoresNick.getText())+1;
            DobladoresNick.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_addDoblaje1ActionPerformed

    private void removeDoblaje1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDoblaje1ActionPerformed
        if (Integer.parseInt(DobladoresNick.getText()) == 1){
            JOptionPane.showMessageDialog(null, "NO SE PUEDE DEJAR UN DEPARTAMENTO SIN TRABAJADORES");
        } else{
            int nuevo = Integer.parseInt(DobladoresNick.getText())-1;
            DobladoresNick.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removeDoblaje1ActionPerformed

    private void addPlotTwist1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlotTwist1ActionPerformed
        if (calculateQuantityN() == 12){
            JOptionPane.showMessageDialog(null, "SE HA SUPERADO LA CANTIDAD LIMITE DE TRABAJADORES!");
        } else {
            int nuevo = Integer.parseInt(GuionistasPlotTwistsNick.getText())+1;
            GuionistasPlotTwistsNick.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_addPlotTwist1ActionPerformed

    private void removePlotTwist1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePlotTwist1ActionPerformed
        if (Integer.parseInt(GuionistasPlotTwistsNick.getText()) == 1){
            JOptionPane.showMessageDialog(null, "NO SE PUEDE DEJAR UN DEPARTAMENTO SIN TRABAJADORES");
        } else{
            int nuevo = Integer.parseInt(GuionistasPlotTwistsNick.getText())-1;
            GuionistasPlotTwistsNick.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removePlotTwist1ActionPerformed

    private void addEnsamblador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEnsamblador1ActionPerformed
        if (calculateQuantityN() == 12){
            JOptionPane.showMessageDialog(null, "SE HA SUPERADO LA CANTIDAD LIMITE DE TRABAJADORES!");
        } else {
            int nuevo = Integer.parseInt(EnsambladoresNick.getText())+1;
            EnsambladoresNick.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_addEnsamblador1ActionPerformed

    private void removeEnsamblador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEnsamblador1ActionPerformed
        if (Integer.parseInt(EnsambladoresNick.getText()) == 1){
            JOptionPane.showMessageDialog(null, "NO SE PUEDE DEJAR UN DEPARTAMENTO SIN TRABAJADORES");
        } else{
            int nuevo = Integer.parseInt(EnsambladoresNick.getText())-1;
            EnsambladoresNick.setText(String.valueOf(nuevo));
        }
    }//GEN-LAST:event_removeEnsamblador1ActionPerformed

    private void txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActionPerformed
        String quantities = GuionistasNick.getText() + ", " + EscenariosNick.getText() + ", " + AnimadoresNick.getText() + ", " + DobladoresNick.getText() + ", " + GuionistasPlotTwistsNick.getText() + ", " + EnsambladoresNick.getText() + " / " + GuionistasDisney.getText() + ", " + EscenariosDisney.getText() + ", " + AnimadoresDisney.getText() + ", " + DobladoresDisney.getText() + ", " + GuionistasPlotTwistsDisney.getText() + ", " + EnsambladoresDisney.getText();
        String data = dia.getText() + " / " + ammount.getText();

        // DATOS INICIALES
        File fichero = new File("DatosIniciales.txt");
        String contenido = "";

        try{
            PrintWriter salida = new PrintWriter(fichero);
            salida.print(data);
            salida.close();
        }catch(Exception e){
            System.out.println(e);
        }

        // CANTIDADES INICIALES

        fichero = new File("InitialQuantity.txt");

        try{
            PrintWriter salida = new PrintWriter(fichero);
            salida.print(quantities);
            salida.close();
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_txtActionPerformed

    private int calculateQuantityN(){
        int cantidadTotal = Integer.parseInt(GuionistasNick.getText()) + Integer.parseInt(EscenariosNick.getText()) + Integer.parseInt(AnimadoresNick.getText()) + Integer.parseInt(DobladoresNick.getText()) + Integer.parseInt(GuionistasPlotTwistsNick.getText()) + Integer.parseInt(EnsambladoresNick.getText());
        System.out.println(cantidadTotal);
        return cantidadTotal;
    }
    
    private int calculateQuantityD(){
        int cantidadTotal = Integer.parseInt(GuionistasDisney.getText()) + Integer.parseInt(EscenariosDisney.getText()) + Integer.parseInt(AnimadoresDisney.getText()) + Integer.parseInt(DobladoresDisney.getText()) + Integer.parseInt(GuionistasPlotTwistsDisney.getText()) + Integer.parseInt(EnsambladoresDisney.getText());
        return cantidadTotal;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnimacionesSavedLabel;
    private javax.swing.JLabel AnimacionesSavedLabelD;
    private javax.swing.JLabel AnimadoresDisney;
    private javax.swing.JLabel AnimadoresNick;
    private javax.swing.JPanel ConfigurationDashboard;
    private javax.swing.JPanel DisneyDash;
    private javax.swing.JLabel DobladoresDisney;
    private javax.swing.JLabel DobladoresNick;
    private javax.swing.JLabel EnsambladoresDisney;
    private javax.swing.JLabel EnsambladoresNick;
    private javax.swing.JLabel EscenariosDisney;
    private javax.swing.JLabel EscenariosNick;
    private javax.swing.JLabel EscenariosSavedLabel;
    private javax.swing.JLabel EscenariosSavedLabelD;
    private javax.swing.JLabel GuionesSavedLabel;
    private javax.swing.JLabel GuionesSavedLabelD;
    private javax.swing.JLabel GuionistasDisney;
    private javax.swing.JLabel GuionistasNick;
    private javax.swing.JLabel GuionistasPlotTwistsDisney;
    private javax.swing.JLabel GuionistasPlotTwistsNick;
    private javax.swing.JPanel NickelodeonDash;
    private javax.swing.JButton addAmmount;
    private javax.swing.JButton addAnimador1;
    private javax.swing.JButton addAnimador2;
    private javax.swing.JButton addDia;
    private javax.swing.JButton addDoblaje1;
    private javax.swing.JButton addDoblaje2;
    private javax.swing.JButton addEnsamblador1;
    private javax.swing.JButton addEnsamblador2;
    private javax.swing.JButton addEscenarios1;
    private javax.swing.JButton addEscenarios2;
    private javax.swing.JButton addGuionista2;
    private javax.swing.JButton addGuionista3;
    private javax.swing.JButton addPlotTwist1;
    private javax.swing.JButton addPlotTwist2;
    private javax.swing.JLabel ammount;
    private javax.swing.JLabel animadorLabel1;
    private javax.swing.JLabel animadorLabel2;
    private javax.swing.JLabel capsPlotTwistReadyLabel;
    private javax.swing.JLabel capsPlotTwistReadyLabel1;
    private javax.swing.JLabel capsReadyLabel;
    private javax.swing.JLabel capsReadyLabel1;
    private javax.swing.JLabel costosLabel;
    private javax.swing.JLabel costosLabelDisney;
    private javax.swing.JLabel costosLabelText;
    private javax.swing.JLabel costosLabelText1;
    private javax.swing.JLabel costosLabelText2;
    private javax.swing.JLabel costosLabelText3;
    private javax.swing.JLabel dayDuration;
    private javax.swing.JLabel daysPassedLabelD;
    private javax.swing.JLabel daysPassedLabelN;
    private javax.swing.JLabel deadline;
    private javax.swing.JLabel deadlineLabel;
    private javax.swing.JLabel deadlineLabelDisney;
    private javax.swing.JLabel deadlineLabelText;
    private javax.swing.JLabel deadlineLabelText1;
    private javax.swing.JLabel dia;
    private javax.swing.JLabel dinseyFondo;
    private javax.swing.JLabel directorStatus;
    private javax.swing.JLabel directorStatusDisney;
    private javax.swing.JLabel directorStatusLabel;
    private javax.swing.JLabel directorStatusLabelD;
    private javax.swing.JLabel discountedLabel;
    private javax.swing.JLabel discountedLabelDisney;
    private javax.swing.JLabel discountedLabelText;
    private javax.swing.JLabel discountedLabelText1;
    private javax.swing.JLabel doblajeLabel1;
    private javax.swing.JLabel doblajeLabel2;
    private javax.swing.JLabel doblajesSavedLabel3;
    private javax.swing.JLabel doblajesSavedLabelD;
    private javax.swing.JLabel ensambladorLabel1;
    private javax.swing.JLabel ensambladorLabel2;
    private javax.swing.JLabel escenariosLabel1;
    private javax.swing.JLabel escenariosLabel2;
    private javax.swing.JLabel faultsLabel;
    private javax.swing.JLabel faultsLabelDisney;
    private javax.swing.JLabel faultsLabelText;
    private javax.swing.JLabel faultsLabelText1;
    private javax.swing.JLabel gananciaLabelText;
    private javax.swing.JLabel gananciaLabelText1;
    private javax.swing.JLabel gananciasLabel;
    private javax.swing.JLabel gananciasLabelDisney;
    private javax.swing.JLabel guionistasLabel1;
    private javax.swing.JLabel guionistasLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel plotTwistLabel1;
    private javax.swing.JLabel plotTwistLabel2;
    private javax.swing.JLabel plotTwistsSavedLabel4;
    private javax.swing.JLabel plotTwistsSavedLabelD;
    private javax.swing.JLabel pmStatus;
    private javax.swing.JLabel pmStatusDisney;
    private javax.swing.JLabel pmStatusLabel;
    private javax.swing.JLabel pmStatusLabelD;
    private javax.swing.JLabel qttyAnimacionesSavedDisney;
    private javax.swing.JLabel qttyAnimacionesSavedNick;
    private javax.swing.JLabel qttyDoblajesSavedDisney;
    private javax.swing.JLabel qttyDoblajesSavedNick;
    private javax.swing.JLabel qttyEscenariosSavedDisney;
    private javax.swing.JLabel qttyEscenariosSavedNick;
    private javax.swing.JLabel qttyGuionesSavedDisney;
    private javax.swing.JLabel qttyGuionesSavedNick;
    private javax.swing.JLabel qttyPlotTwistsCapsReadyDisney;
    private javax.swing.JLabel qttyPlotTwistsCapsReadyNick;
    private javax.swing.JLabel qttyPlotTwistsSavedDisney;
    private javax.swing.JLabel qttyPlotTwistsSavedNick;
    private javax.swing.JLabel qttyStandardCapsReadyDisney;
    private javax.swing.JLabel qttyStandardCapsReadyNick;
    private javax.swing.JButton removeAmmount;
    private javax.swing.JButton removeAnimador1;
    private javax.swing.JButton removeAnimador2;
    private javax.swing.JButton removeDia;
    private javax.swing.JButton removeDoblaje1;
    private javax.swing.JButton removeDoblaje2;
    private javax.swing.JButton removeEnsamblador1;
    private javax.swing.JButton removeEnsamblador2;
    private javax.swing.JButton removeEscenarios1;
    private javax.swing.JButton removeEscenarios2;
    private javax.swing.JButton removeGuionista2;
    private javax.swing.JButton removeGuionista3;
    private javax.swing.JButton removePlotTwist1;
    private javax.swing.JButton removePlotTwist2;
    private javax.swing.JButton txt;
    private javax.swing.JLabel utilidadesLabel;
    private javax.swing.JLabel utilidadesLabelDisney;
    // End of variables declaration//GEN-END:variables
}
